apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubby-meteor-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubby-meteor-clusterRole
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubby-meteor-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubby-meteor-clusterrole
subjects:
  - kind: ServiceAccount
    name: kubby-meteor-service-account
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubby-meteor
  name: kubby-meteor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubby-meteor
  strategy: {}
  template:
    metadata:
      labels:
        app: kubby-meteor
    spec:
      serviceAccountName: kubby-meteor-service-account
      containers:
        - name: kubby-meteor
          image: ndoolan/kubby-meteor:2.4
          ports:
            - containerPort: 8000
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubby-meteor
  name: kubby-meteor
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: kubby-meteor
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: faros-scope
  name: faros-scope
spec:
  containers:
    - env:
        - name: NODE_ENV
          value: prod
      image: marcoalagna/faros-scope:latest
      name: faros-scope
      ports:
        - containerPort: 3000
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: faros-scope
  name: faros-scope
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    run: faros-scope
  type: LoadBalancer
status:
  loadBalancer: {}
